@contentType = application/json
@baseUrl = http://localhost:3333
@baseUrlDirectModule = {{baseUrl}}/transactions


###
GET {{baseUrlDirectModule}}/
Content-Type: {{contentType}}


###
POST {{baseUrlDirectModule}}/create
Content-Type: {{contentType}}

{
 "title": "Pagamentos",
 "amount": 213,
 "type":"debit"
}